### ISSUE TITLE
Increment package version

### ISSUE THREAD

**Issue by aksenk** [ahes/prometheus-barman-exporter#13]
Hello. 

You recently accepted a pull request https://github.com/ahes/prometheus-barman-exporter/pull/12.

Could you increment package version please?

In repository we can see version [1.0.7](https://github.com/ahes/prometheus-barman-exporter/blob/master/setup.py#L4)

But in pip3 repos I see 1.0.8 version

```
pip3 search barman_exporter
barman_exporter (1.0.8)  - Barman exporter for Prometheus
```

But version 1.0.8 also does not contain changes from [this](https://github.com/ahes/prometheus-barman-exporter/pull/12) MR.

**Comment by ahes** [comment]
Bumped up package version to 1.0.9. Thanks for reporting.
