### ISSUE TITLE
Error when no backups for a server

### ISSUE THREAD

**Issue by svinther** [ahes/prometheus-barman-exporter#14]
Hello, I get this error if there is a server in the list with no backups yet

`ValueError: time data 'None' does not match format '%Y%m%dT%H%M%S'`

The program exists so the remaining servers are not considered, and also a temp file is left

As a workaround I currently do like this:

```
for s in $(barman list-server); do /usr/local/bin/barman-exporter -f /tmp/barman-$s.prom -u node-exp -g node-exp $s && mv -f /tmp/barman-$s.prom /var/lib/node_exporter; done 2>&1 | systemd-cat -t barman-exporter
```

/Steffen

**Comment by silencej** [comment]
This pull request has fixed it: https://github.com/ahes/prometheus-barman-exporter/pull/12
However, the v1.0.8 in pypi is still the old version.

**Comment by ahes** [comment]
I bumped up package version. Should work now.
