### ISSUE TITLE
Python module based exporter does not update metric values

### ISSUE THREAD

**Issue by siepkes** [ahes/prometheus-barman-exporter#5]
I'm using the Python module based exporter with Barman 2.9 and Python 3.6 on SmartOS (Solaris derivative) and the values of the metrics don't get updated. The values of the metrics are set a single time when the script is started and then they stay the same forever.

This could be due to the fact that I'm running my setup on a somewhat more exotic setup (SmartOS) but I don't really see how this could have such an effect. I did a quick search in barman's source to see if it uses some platform specific things like inotify but I can't find anything of the sort.

I suspect this might be more likely caused by barman 2.9 which was released a couple of weeks ago. Can anyone confirm if they have a working setup with barman 2.9?

**Comment by darkl0rd** [comment]
I have the exact same problem running Barman 2.9. Also, one also needs to restart the exporter for it to pickup newly added targets.

**Comment by anhsaoxanh14** [comment]
Yes. I have the same issue. When i perform new barman backup. Metrics about total backup does not update

**Comment by darkl0rd** [comment]
@ahes just revisited this, same issue still in Barman 2.10. I had a look through the code, and it seems that "output" is not being refreshed on subsequent calls.

**Comment by ahes** [comment]
@darkl0rd @anhsaoxanh14 @siepkes Thanks for reporting. I rewrote the code to use experimental JSON support I added to Barman 2.9. Now barman exporter parses barman command output directly.  

I will leave this issue open for a while to let you check if any problems with the new code. Let me know.

**Comment by darkl0rd** [comment]
It works, but the performance is absolutely horrible. I tested with about 30 databases, the exporter takes almost 6 minutes before it returns. Executing the check command directly finishes in 26s.

**Comment by ahes** [comment]
@darkl0rd That is normal. `backup-list` command takes a significantly long time to execute.
I am thinking of storing these metrics in a file that will be passed to Prometheus immediately and refreshed from time to time.

**Comment by darkl0rd** [comment]
Yes, definitely needs a cache. 
Performing the check costs quite some CPU and you can’t rely on the exporter to ever finish in time as it stands (scrape internal > 5m being ill-advised).

**Comment by ahes** [comment]
@darkl0rd I changed barman-exporter and now it saves the metrics to textfile. I suggest running every hour. Have a nice day!

**Comment by darkl0rd** [comment]
@ahes This means it should now be used in combination with for example 'node-exporter'? I would prefer if it indeed did run standalone (like before), but with improved performance; e.g. through using a cache as per your own suggestion.

**Comment by ahes** [comment]
@darkl0rd Well, usually using Prometheus you have node-exporter running anyway. If you prefer standalone you can just run node-exporter and disable every single collector leaving textfiles processing from the directory where barman-exporter dumps the textfile.

Alternatively, you can run a simple http server from systemd:

```
WorkingDirectory=/var/lib/barman-exporter
User=nobody
ExecStart=/usr/bin/python3 -m http.server -b 10.10.10.10 9123
```

Having a cron job with barman-exporter saving to /var/lib/barman-exporter/metrics file.
Then requesting http://10.10.10.10:9123/metrics will return metrics to prometeus.

**Comment by darkl0rd** [comment]
Sure, however it becomes a bit more interesting when you have everything dockerized. I have dozens of Barman instances (one per database container) and an equal amount of side-cars running the prometheus exporter. Getting the data to node-exporter is possible by sharing a filesystem, but is far from ideal. 

Why not have this exporter (optionally) expose the http server, and make caching of the contents a parameter?

**Comment by ahes** [comment]
@darkl0rd The idea doesn't sound that bad. I uploaded the new code. Try for yourself.
